services:
  bot:
    build: .
    container_name: mokafih-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mokafih_net

  db:
    image: postgres:15-alpine
    container_name: mokafih-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mokafih_user
      POSTGRES_PASSWORD: StrongPassword123
      POSTGRES_DB: mokafih_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mokafih_user -d mokafih_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mokafih_net

volumes:
  postgres_data:

networks:
  mokafih_net:
    driver: bridge
